# Generated by Django 3.0.3 on 2020-02-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='Null', upload_to='images/'),
        ),
    ]
