FROM alpine
 
RUN apk update
RUN apk add wget curl

RUN curl https://speed.hetzner.de/100MB.bin > speed_test.txt
 
CMD mkdir /var/www/
CMD mkdir /var/www/html/
 
WORKDIR /var/www/html/
 
COPY Dockerfile.tar.gz /tmp/
RUN tar -zxvf /tmp/Dockerfile.tar.gz -C /var/www/html/
RUN rm /tmp/Dockerfile.tar.gz

RUN cat Dockerfile_ver1

